# Generated by Django 2.2.12 on 2020-06-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0018_auto_20200615_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='from_task_ref',
            field=models.TextField(blank=True, verbose_name='reference from task'),
        ),
    ]
