# Generated by Django 2.2.12 on 2020-06-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0019_auto_20200612_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='generated_from_task',
        ),
    ]
