# Generated by Django 2.2.12 on 2020-06-15 13:01

from django.db import migrations

def migrate_source_tasks(apps, schema_editor):
    UserStory = apps.get_model("userstories", "UserStory")
    stories = UserStory.objects.select_related("generated_from_task").filter(generated_from_task__isnull=False)
    for story in stories:
        story.from_task_info = "#%s" % story.generated_from_task.ref


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0019_userstory_from_task_info'),
    ]

    operations = [
        migrations.RunPython(migrate_source_tasks)
    ]
