# Generated by Django 2.2.12 on 2020-06-15 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0020_auto_20200615_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='generated_from_task',
        ),
    ]
